### ISSUE TITLE
LYNX | 1.0 | HOUDINI | LYNX_force_general | Question about usage

### ISSUE THREAD

**Issue by MostHated** [LucaScheller/VFX-LYNX#1]
Hey there, 

 This tool looks great and it seems like it might be able to provide me with exactly the thing I have been looking for. I have been learning to make small cinematic clips in Unity and could not find any good looking blood effects so I grabbed Houdini Indie to see if I could make and export something in Alembic or whatever ends up being best but I keep having issue trying to apply force to a pop fluid in such a way that looks/acts anywhere close to what I am after.

Here is what I currently have: https://i.imgur.com/BMN4Cro.mp4

This is what I am hoping to create: https://vimeo.com/167353334

I am new to Houdini, and just found your plugin about an hour ago, but I was hoping you might be able to point me in the right direction as to what would be the best course of action to take using your plugin that would help me achieve the sudden and impactful spray of a pop fluid similar to the video above? So far in my own tests I end up simply getting a steady stream when trying to apply velocity or force as seen here: https://i.imgur.com/GistqQf.mp4

Any tips or tricks you might be able to provide as to the settings to use in your tool would be extremely appreciated!
Thanks,
-MH

**Comment by MostHated** [comment]
Turns out, it was a lot more simple to figure out than I expected. :D

At least it is definitely a step in the right direction.
https://i.imgur.com/fIW9Ltb.mp4

**Comment by MostHated** [comment]
If anyone in the future reads this, let it be an extremely positive review for this asset. It only took me (a complete Houdini novice) about 30 minutes or an hour to get this all figured out after spending a week or a week and a half trying to watch different tutorials on how to apply velocity/force different ways to try and get the effect I was after. I loaded this asset up and bam, was able to make exactly what I was after in no time. Huge thanks for making and sharing this awesome asset!

Here is my first rough import into Unity, looking great so far with barely any tweaking done yet. 
https://i.imgur.com/3BVAsqV.mp4

**Comment by LucaScheller** [comment]
Hi, sorry for answering so late, I took a small Christmas break. Looks good for a first iteration! Thank you so much for the positive feedback and the kind words:) Made my day!

Let me know if you have any more questions, you can also find a more in-depth tutorial about the LYNX_force on my [vimeo channel](https://vimeo.com/325545103), although there have been quite a few new features since the release of the video. If you have any feature requests or if you find any bugs, please notify me:) 

All the best and Happy New Year :)
-Luca

**Comment by MostHated** [comment]
Hey there,
    No worries, I hope you had a great vacation.  Finding this definitely made my day as well, lol. I did have another question, though, if you don't mind? I was attempting to use a torus as both the input geometry as well as the shape for the force and then the bitangent force in hopes that it would cause the particles to swirl in a circular motion around the torus, which it sort of did for about half of a revolution but then they all started to shoot off different directions. What I am wondering though, is how I might adjust the settings so that instead of shooting off and flying away, they would more or less maintain an orbit around the shape of the torus to make a neat swirly ring?

Thanks!
-MH

**Comment by LucaScheller** [comment]
Hi MH,
would you mind sharing a scene file? Then I would be happy to dial in the necessary settings :)
Thanks!
-Luca

**Comment by MostHated** [comment]
Sure thing. I don't know if there is a typical or common way to share these files (like imgur, but for houdini files?) but I figured google drive should do the trick. https://drive.google.com/file/d/14erAkM-0QQT9tDssVQK1nr2anXpZEZzo/view

I definitely appreciate it.
Thanks,
-MH

**Comment by LucaScheller** [comment]
Hi MH,
I usually just upload them on odforce or my website;)

Here you go: [Download File](https://www.lucascheller.de/A_CMS/wordpress/wp-content/uploads/2020/01/LYNX_GitHub_Issue_1_v0001.hipnc)

I've made the following changes (I only have access to a Houdini Non-Commercial Version right now, so make sure to make the actual changes in your original file):
- Hide On Playback and Streamer Guides are on for a better viewport visualization
- Randomize Strength is on to break up the look.
- Increased torus width
- Slightly increased Vdb Size to avoid artifacts

The rest is just playing with the "Volume" Strengths and the torus width to keep the particles inside the shape. You can also add some noise to make it more random :) I've also documented the changes in the file and added a second force with a bit more swirl for you to try out.

Cheers,
Luca

**Comment by MostHated** [comment]
Oh man, that is great. I especially like the initial burst/scatter outward of points followed by the maintained swirl. Thanks a ton. I am definitely going to dig deeper into this. Part of the issue is I have only been using Houdini for 2-3 weeks or so now, so I really just don't know all of the different nodes yet, or how they work. So having examples I can play around with like this that include things I never used (like that point velocity) and then the comments and such on top of it help me learn a lot faster. 

With the increase of the VDB size you did, and another tutorial I followed used a vdbfromparticles node, I need to research exactly what a vdb is, does, and is used for. I thought I understood it, but I think I mistook the acronym and associated it with rigid body dynamics for some reason. 

One last question I have has to do with the life expectancy, which I suppose also applies to most any attribute when animating, but when you animate a value and particles are spawned, does the value apply exactly what the current interpolated value is on that frame, and it is only applying it to the particles that are spawned on that same frame or is it applying the value to all spawned particles which are associated with whatever attribute you are modifying?

An example being modifying the life expectancy (shortening to LE) from 2 to 10 starting on frame 1 and then on frame 2 it begins an interpolation between 2 and 10, so does that mean any particles spawned on frame 1 have a LE of 2, but then on frame 2 more particles are spawned and only those particular particles now have a LE of 2.xx or whatever it is, but the particles from frame 1 still have an LE of 2, or do those particles from frame 1 end up with an LE of whatever the overall LE is at the time of the frame? I hope that makes sense, lol.

Thanks again!
-MH

**Comment by LucaScheller** [comment]
VDBs are essentially sparse volumes. I use them in the calculation process of the force because it is faster than point lookups, but as a normal user that shouldn't concern you much. In the case of the LYNX_force just know that if box like artifacts appear, a good idea might be to lower the VDB size parameter in the shape tab.

Animating parameters has a different effect per node (e.g. some nodes add/subtract/overwrite etc.).
Incase of the "Pop Source" node, the life expectancy parameter sets the value of the "life" point attribute for the particles that were sourced on that frame via that node. As soon as the age becomes higher than the life attribute value those particles are deleted.

Hope that makes sense,
Cheers,
Luca
![LifeExpectency](https://user-images.githubusercontent.com/38698429/71661111-7bbdf600-2d4d-11ea-9b4e-43e78d88dc63.png)
